### ISSUE TITLE
Discord advanced Application Command Permission System

### ISSUE THREAD

**Issue by yoyosource** [discord-jda/JDA#2719]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://github.com/discord-jda/JDA/releases/latest)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

https://github.com/discord/discord-api-docs/blob/main/docs/interactions/Application_Commands.md#permissions

**Comment by MinnDevelopment** [comment]
Thanks for your detailed feature request, since this is an OAuth2 feature it is out of scope for JDA at this time. JDA only supports endpoints for the bot API, which requires a bot token instead of an OAuth access token.

To use this API, you must implement an OAuth2 server that performs a token exchange with the authorization of an administrator that can configure integration permissions. Then, with the access token from that exchange, you are able to use these endpoints.

Since this is basic OAuth2, it can easily be done manually using any OAuth2 client library. There isn't much that JDA can do to help out, since it can't offer an OAuth server.

**Comment by yoyosource** [comment]
Thanks for the quick response and the Idea of how to use it.
